# Generated by Django 4.0.4 on 2022-06-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_car_created_car_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-created', '-created')},
        ),
        migrations.CreateModel(
            name='ContactSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
                ('sub', models.CharField(max_length=90)),
                ('message', models.TextField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.user')),
            ],
        ),
    ]
