# Generated by Django 4.0.4 on 2022-06-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_options_contactsections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSections',
            new_name='ContactSection',
        ),
    ]
